repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-ast
      - id: check-yaml

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        args: ["--check", "--diff"]

      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        args: ["--check", "--diff"]

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
        args: ["--config=.flake8"]
