[auth]
provider = "r2r"
access_token_lifetime_in_minutes = 60
refresh_token_lifetime_in_days = 7
require_authentication = false
require_email_verification = false
default_admin_email = "admin@example.com"
default_admin_password = "change_me_immediately"

[completion]
provider = "litellm"
concurrent_request_limit = 16

  [completion.generation_config]
  model = "openai/gpt-4o"
  temperature = 0.1
  top_p = 1
  max_tokens_to_sample = 1_024
  stream = false
  add_generation_kwargs = { }

[crypto]
provider = "bcrypt"

[database]
provider = "postgres"

[embedding]
provider = "litellm"
base_model = "text-embedding-3-small"
base_dimension = 512
batch_size = 128
add_title_as_prefix = false
rerank_model = "None"
concurrent_request_limit = 256

[eval]
provider = "None"

[ingestion]
  [[ingestion.override_parsers]]
  document_type = "pdf"
  parser = "PDFParserUnstructured"

  [ingestion.text_splitter]
  type = "recursive_character"
  chunk_size = 512
  chunk_overlap = 20

[kg]
provider = "None"

[logging]
provider = "local"
log_table = "logs"
log_info_table = "log_info"

[prompt]
provider = "r2r"
