name: Debian R2R Docker Build and Integration Test Local (Debian GNU/Linux 12 (bookworm) amd64)

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: [ self-hosted, Linux ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python virtual environment
      run: |
        python3 -m venv $HOME/r2r_local_venv
        echo "$HOME/r2r_local_venv/bin" >> $GITHUB_PATH

    - name: Activate virtual environment and install R2R
      run: |
        . $HOME/r2r_local_venv/bin/activate
        pip install --upgrade pip
        pip install --upgrade r2r

    - name: Run Docker with the Ollama Docker Extension
      run: |
        r2r --config-name=local_ollama serve --docker --docker-ext-ollama

    - name: Install Ollama Models
      run: |
        docker exec r2r-ollama-1 ollama pull llama3
        docker exec r2r-ollama-1 ollama pull mxbai-embed-large

    - name: Run integration tests
      run: |
        echo "R2R Version"
        r2r version

        echo "Ingest Data"
        r2r ingest-sample-file

        echo "Get Documents Overview"
        r2r documents-overview

        echo "Get Document Chunks"
        r2r document-chunks 93123a68-d668-51de-8291-92162730dc87

        echo "Delete Documents"
        r2r delete --keys=document_id --values=b736292c-11e6-5453-9686-055da3edb866

        echo "Vector Search"
        r2r search --query="What was Uber's profit in 2020?"

        echo "Hybrid Search"
        r2r search --query="What is a fierce nerd?" --do-hybrid-search

        echo "Basic RAG"
        r2r rag --query="What was Uber's profit in 2020?"

        echo "RAG with Hybrid Search"
        r2r rag --query="Who is John Snow?" --do-hybrid-search

        echo "Streaming RAG"
        r2r rag --query="What was Lyft's profit in 2020?" --stream

        echo "Users Overview"
        r2r users-overview

        echo "Logging"
        r2r logs

        echo "Stop Docker"
        r2r docker-down


    - name: Clean up
      if: always()
      run: |
        rm -rf $HOME/r2r_local_venv
        docker system prune -af --volumes
