name: Deploy Docker on Release

on:
  release:
    types: [created]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: emrgntcmplxty/r2r:latest,emrgntcmplxty/r2r:${{ github.event.release.tag_name }}
